server:
  port: 8070
eureka:
  instance:
    hostname: localhost

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: eureka-server 
  cloud:
    config: 
       enabled: true
       #uri: http://configserver:8888 
       uri: http://localhost:8888

management:
   endpoints:
     web:
       exposure:
         include:
         - health,info,refresh
   endpoint:
     restart:
       enabled: true
     refresh:
       enabled: true